# Builds the package and runs all tests.
name: CI

on:
  push:
    branches-ignore:
      - master
      - develop
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Setup NodeJS v10
        uses: actions/setup-node@v2
        with:
          node-version: '10'

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install modules
        run: npm install --no-audit --ignore-scripts

      - name: Lint
        run: npm run lint

      - name: Build package
        run: npm run build-package

      - name: Run unit tests
        run: npm run test

