# Builds the package and runs all tests.
name: CI

on:
  push:
    branches-ignore:
      - master
      - develop
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.ref }}
        cancel-in-progress: true

    steps:
      - name: Setup NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci --no-audit --ignore-scripts

      - name: Lint
        run: npm run lint

      - name: Build package
        run: npm run build-package

      - name: Run unit tests
        run: npm run test

